import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <Navbar />
          <div className="min-h-screen flex justify-center items-center bg-white">
            {/* bg-gradient-to-r from-[#16181a] via-[#1e2325] to-[#16181a] */}
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
